# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehendge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='gathered_energy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
