# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehendge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='encoded_polyline',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
