# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehendge', '0002_station_gathered_energy'),
        ('gamehendge', '0002_path_encoded_polyline'),
    ]

    operations = [
    ]
