# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehendge', '0003_merge_20170916_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.IntegerField(choices=[(1, b'red'), (2, b'blue')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='gathered_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='station',
            name='team',
            field=models.IntegerField(),
        ),
    ]
