# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehendge', '0004_auto_20170919_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='mook',
            name='health',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='station',
            name='health',
            field=models.IntegerField(default=100),
        ),
    ]
